# Site wide configuration
title: "VEIDA Lab"
subtitle: "York University"
description: "VEIDA Lab - Department of Electrical and Computer Engineering - York University."
logo: veida-logo-orange-light.png # 120x120 px default image used for Twitter summary card
teaser: veida-teaser-709x443.png # 400x250 px default teaser image used in image archive grid
bannerimg: veida-banner4.jpg
locale: en
url: http://www.veidalab.com
feed:
  path: atom.xml

# Contact Info
email: admin@veida.ca
phone: "+ 416 736 2100  x 33965"
organization: "York University"
department: "Department of Electrical and Computer Engineering"
address: "4700 Keele Street"
city: Toronto
state: Ontario
country: Canada
zip_code: "M3J 1P3"

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - html-proofer
  - jekyll-seo-tag

# Site owner
owner:
  name: Brad Stimpson
  email: brad@cse.yorku.ca
  twitter: bstimpson
  google:
    ad-client:
    ad-slot:
  bio: 
  avatar: bio-photo.jpg 
  disqus-shortname: bradford2015


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
